# Netlify configuration for Create React App

[build]
  # This command is run to build the site
  command = "npm run build"
  # The directory to publish, relative to the base directory
  publish = "build"
  # The base directory to run the build command from
  base = "frontend"

# Redirects rule for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
